[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkcs1 = "0.7.5"
dotenv = "0.15.0"
actix-web = "4.3.1"
tokio = "1.28.0"
